# Generated by Django 2.1.5 on 2019-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=80)),
                ('presentacion', models.IntegerField()),
                ('precio_Ingreso', models.FloatField()),
                ('precio_Venta', models.FloatField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nombre', 'codigo')},
        ),
    ]
