# Generated by Django 2.1.5 on 2019-12-13 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=80)),
                ('codigo_Interno', models.CharField(max_length=80)),
                ('presentacion', models.CharField(max_length=80)),
                ('precio_Ingreso', models.FloatField()),
                ('precio_Venta', models.FloatField()),
                ('fecha', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nombre', 'codigo_Interno')},
        ),
    ]
