# Generated by Django 2.1.5 on 2019-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_Interno',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
