# Generated by Django 2.1.5 on 2019-11-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=80)),
                ('Codigo', models.CharField(max_length=80)),
                ('Registro_Invima', models.CharField(max_length=80)),
                ('Presentacion', models.IntegerField()),
                ('Precio_Ingreso', models.FloatField()),
                ('Precio_Venta', models.FloatField()),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
