# Generated by Django 2.1.5 on 2019-11-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_Ingreso', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Codigo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Precio_Ingreso',
            new_name='precio_Ingreso',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Precio_Venta',
            new_name='precio_Venta',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Presentacion',
            new_name='presentacion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Registro_Invima',
            new_name='registro_Invima',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nombre', 'codigo')},
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inventory_app.Product'),
        ),
    ]
