# Generated by Django 2.1.5 on 2019-11-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20191113_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('fecha_Ingreso', models.DateField(auto_now=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existings', to='inventory_app.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='producto',
        ),
        migrations.DeleteModel(
            name='InventoryModel',
        ),
    ]
