# Generated by Django 2.1.5 on 2019-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20191113_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='codigo',
            field=models.CharField(max_length=80),
        ),
    ]
