# Generated by Django 2.1.5 on 2019-12-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_auto_20191216_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', to_field='nombre'),
        ),
    ]
